function startdate = getGCDCstartdate(filename)
%IMPORTFILE Import data from a text file
%  DATA004 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a string array.
%
%  DATA004 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  DATA004 = getGCDCstartdate("C:\Users\ccblack\Documents\Carson\Projects\IOD_activeRFID\DATA-004.CSV", [3, 3]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 14-Nov-2022 10:23:24

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
dataLines = [3, 3];
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "httpwwwgcdataconceptscom", "x161d", "Var4"];
opts.SelectedVariableNames = ["httpwwwgcdataconceptscom", "x161d"];
opts.VariableTypes = ["string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "httpwwwgcdataconceptscom", "x161d", "Var4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "httpwwwgcdataconceptscom", "x161d", "Var4"], "EmptyFieldRule", "auto");

% Import the data
startdate = readmatrix(filename, opts);

end