function [DATA,starttime] = importGCDCaccelerometer(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DATA004 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  DATA004 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  DATA004 = importfile("E:\GCDC\DATA-004.CSV", [9, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Nov-2022 14:52:57

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [9, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "Ax", "Ay", "Az"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
DATA = readtable(filename, opts);

% Start date
timestr = getGCDCstartdate(filename);
DAY=datetime(timestr(1),"Format",'uuuuMMdd','TimeZone','UTC'); %convert Date to UTC datetime
TIME=datetime(timestr(2),"Format",'HHmmss','TimeZone','UTC'); %convert time to UTC datetime
starttime=datetime(DAY+timeofday(TIME),"Format",'uuuuMMdd''T''HHmmss','TimeZone','UTC'); %add DAY and TIME

end