function aRFIDcobbleLog1 = readARFIDcobbleLog(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ARFIDCOBBLELOG1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  ARFIDCOBBLELOG1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  aRFIDcobbleLog1 = importfile("C:\Users\ccblack\Documents\Carson\Projects\IOD_activeRFID\ActiveCobbleData\aRFIDcobbleLog_20220809.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Aug-2022 11:44:56

%% Input handling

% If dataLines is not specified, define defaults (skip header names by default)
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["UTCtime", "TagID", "Lat", "Lon", "notes"];
opts.VariableTypes = ["string", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "UTCtime", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["UTCtime", "notes"], "EmptyFieldRule", "auto");

% Import the data
aRFIDcobbleLog1 = readtable(filename, opts);

end